# dbt will search the current working directory for the profiles.yml file and will default to the ~/.dbt/ directory if not found.

dbt_starter:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
